export const CONNECTION_STEP_EMAIL = 'CONNECTION_STEP_EMAIL';
export const  CONNECTION_STEP_PASSWORD = 'CONNECTION_STEP_PASSWORD';
export const CONNECTION_STEP_CODE = 'CONNECTION_STEP_CODE';
export const CONNECTION_STEP_FORGETPASSWORD = 'CONNECTION_STEP_FORGETPASSWORD';
export const CONNECTION_STEP_CONGRATULATION = 'CONNECTION_STEP_CONGRATULATION';

export const FORM_CONNECTION = 'Login';
export const FORM_REGISTRATION = 'Registration';
export const FORM_FORGETPWD = 'ForgetPswdForm'
export const REGISTRATION_STEP_CONGRATULATION = 'REGISTRATION_STEP_CONGRATULATION';
export const REGISTRATION_STEP_EMAIL = 'REGISTRATION_STEP_EMAIL';
export const REGISTRATION_STEP_CODE = 'REGISTRATION_STEP_CODE';
export const  REGISTRATION_STEP_PASSWORD = 'REGISTRATION_STEP_PASSWORD';
export const  REGISTRATION_STEP_NAME = 'REGISTRATION_STEP_NAME';
export const  REGISTRATION_STEP_PHONE= 'REGISTRATION_STEP_PHONE';
