export const LOAD_RESTAURANT_DETAILS = 'restaurants/LOAD_RESTAURANT_DETAILS';
export const LOAD_RESTAURANT_DETAILS_SUCCESS =
  'restaurants/LOAD_RESTAURANT_DETAILS_SUCCESS';
export const LOAD_RESTAURANT_DETAILS_ERROR =
  'restaurants/LOAD_RESTAURANT_DETAILS_ERROR';
