export const GET_FAVORITE_RESTAURANTS = 'restaurants/GET_FAVORITE_RESTAURANTS';
export const GET_FAVORITE_RESTAURANTS_SUCCESS =
  'restaurants/GET_FAVORITE_RESTAURANTS_SUCCESS';
export const GET_FAVORITE_RESTAURANTS_ERROR =
  'restaurants/GET_FAVORITE_RESTAURANTS_ERROR';

export const GET_PROFILE = 'profile/GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'profile/GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'profile/GET_PROFILE_ERROR';

export const UPDATE_PROFILE = 'profile/UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'profile/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'profile/UPDATE_PROFILE_ERROR';

export const GET_OPINIONS_USER = 'profile/GET_OPINIONS_USER';
export const GET_OPINIONS_USER_SUCCESS = 'profile/GET_OPINIONS_USER_SUCCESS';
export const GET_OPINIONS_USER_ERROR = 'profile/GET_OPINIONS_USER_ERROR';

export const DELETE_OPINIONS_USER = 'profile/DELETE_OPINIONS_USER';
export const DELETE_OPINIONS_USER_SUCCESS = 'profile/DELETE_OPINIONS_USER_SUCCESS';
export const DELETE_OPINIONS_USER_ERROR = 'profile/DELETE_OPINIONS_USER_ERROR'

export const ADD_OPINIONS_USER = 'profile/ADD_OPINIONS_USER';
export const ADD_OPINIONS_USER_SUCCESS = 'profile/ADD_OPINIONS_USER_SUCCESS';
export const ADD_OPINIONS_USER_ERROR = 'profile/ADD_OPINIONS_USER_ERROR'

export const UPDATE_OPINIONS = 'profile/UPDATE_OPINIONS'

export const UPDATE_FORM_PROFILE = 'profile/UPDATE_FORM_PROFILE';

export const ADD_FAVORITE_TO_USER = 'profile/ADD_FAVORITE_TO_USER';
export const ADD_FAVORITE_TO_USER_SUCCESS = 'profile/ADD_FAVORITE_TO_USER_SUCCESS';
export const ADD_FAVORITE_TO_USER_ERROR = 'profile/ADD_FAVORITE_TO_USER_ERROR';

export const DELETE_FAVORITE_USER = 'profile/DELETE_FAVORITE_USER';
export const DELETE_FAVORITE_USER_SUCCESS = 'profile/DELETE_FAVORITE_USER_SUCCESS';
export const DELETE_FAVORITE_USER_ERROR = 'profile/DELETE_FAVORITE_USER_ERROR';

export const UNBOOKMARK_RESTAURANT = 'profile/UNBOOKMARK_RESTAURANT';


export const GET_RESERVATIONS_USER = 'profile/GET_RESERVATIONS_USER';
export const GET_RESERVATIONS_USER_SUCCESS = 'profile/GET_RESERVATIONS_USER_SUCCESS';
export const GET_RESERVATIONS_USER_ERROR = 'profile/GET_RESERVATIONS_USER_ERROR';
